name: 'Backup Repo to S3'
on:
  schedule:
    - cron: '30 9 * * 5'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: now
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          MIRROR_TARGET: beam-code-backup/repo/beam-salesforce-cartridge/${{ steps.now.outputs.NOW }}
        with:
          args: --overwrite --remove
