name: SFRA CI

on:
  pull_request:
    branches:
    - integration
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.12.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, compile, lint, and test
      run: |
        npm install
        npm run compile:js --if-present
        npm run compile:scss --if-present
        npm run compile:fonts --if-present
        npm run lint
        npm run test
      env:
        CI: true
